"""
Django settings for ict_support project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment
env = environ.Env(
    DEBUG=(bool, False),
)
# Read .env file at project root if present
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(str(env_file))

# Build a default PostgreSQL URL from environment variables (no sqlite fallback)
# If `DATABASE_URL` is provided it will be used; otherwise compose from individual vars.
db_url = env('DATABASE_URL', default=None)
if not db_url:
    pg_name = env('POSTGRES_DB', default='ict_support')
    pg_user = env('POSTGRES_USER', default='postgres')
    pg_password = env('POSTGRES_PASSWORD', default='postgres')
    pg_host = env('POSTGRES_HOST', default='localhost')
    pg_port = env('POSTGRES_PORT', default='5432')
    db_url = f"postgres://{pg_user}:{pg_password}@{pg_host}:{pg_port}/{pg_name}"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-jla3b@+$xvksf=u%uv-8(@0j#9&(ei=^f@mox=i!36hn^lzbtm')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', True)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'users', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ict_support',
    'tickets',
    'notifications',
    'solo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ict_support.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ict_support.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(default=db_url)
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

TICKET_ATTACHMENT_PATH = env('TICKET_ATTACHMENT_PATH', default='ticket_uploads/')

MAX_ATTACHMENT_SIZE_MB = env('MAX_ATTACHMENT_SIZE_MB', default=2, cast=int)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


AUTHENTICATION_BACKENDS = [
    'ict_support.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAuthenticated',
    ],
     'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,  # default per page
}


CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/1")
CELERY_ACCEPT_CONTENT = env("CELERY_ACCEPT_CONTENT", default="json").split(",")
CELERY_TASK_SERIALIZER = env("CELERY_TASK_SERIALIZER", default="json")
CELERY_RESULT_SERIALIZER = env("CELERY_RESULT_SERIALIZER", default="json")
CELERY_TIMEZONE = env("CELERY_TIMEZONE", default="Asia/Dhaka")
CELERY_ENABLE_UTC = env("CELERY_ENABLE_UTC", default="True").lower() in ("true", "1", "yes")
CELERY_BROKER_CONNECTION_TIMEOUT = int(env("CELERY_BROKER_CONNECTION_TIMEOUT",default="2"))
CELERY_BROKER_CONNECTION_RETRY = env("CELERY_BROKER_CONNECTION_RETRY", default="False")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = env("CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP", default = "False")


CELERY_BEAT_SCHEDULE = {
    "retry_unsent_notifications": {
        "task": "notifications.tasks.retry_unsent_notifications",
        "schedule": 60.0,  # every 60 seconds
    },
}
CELERY_TASK_ROUTES = {
    "notifications.tasks.retry_unsent_notifications": {
        "queue": "notifications",
    },
}
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST",default= "localhost")
EMAIL_PORT = int(env("EMAIL_PORT", default="1025"))
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="no-reply@example.com")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD",default= "")


MOBIREACH_USERNAME = env("MOBIREACH_USERNAME")
MOBIREACH_PASSWORD = env("MOBIREACH_PASSWORD")
MOBIREACH_SENDER = env("MOBIREACH_SENDER")
MOBIREACH_URL = env("MOBIREACH_URL")