# Generated by Django 6.0.2 on 2026-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempattachment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
