# Generated by Django 6.0.2 on 2026-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tempattachment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempattachment',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
