# Generated by Django 6.0.2 on 2026-03-12 09:36

import django.core.validators
import ict_support.models
import ict_support.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=ict_support.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), ict_support.validators.validate_file_size, ict_support.validators.validate_mime_type]),
        ),
    ]
