# Generated by Django 6.0.2 on 2026-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_support', '0002_alter_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_app', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
