# Generated by Django 6.0.2 on 2026-03-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_support', '0004_clientuser_staffuser_alter_issuecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='ict_support.issuesubcategory'),
        ),
    ]
