# Generated by Django 6.0.2 on 2026-03-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_support', '0005_alter_ticket_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ict_support.issuesubcategory'),
        ),
    ]
