# Generated by Django 6.0.2 on 2026-02-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active_submitter',
            field=models.BooleanField(default=True),
        ),
    ]
