# Generated by Django 6.0.2 on 2026-03-12 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801XXXXXXXXX'", regex='^\\+?88\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
